# main reference endpoints for fetching current Stacks block height
# polled every 2 minutes
referenceApiNodes:
  - https://stacks-node-api.mainnet.stacks.co

# maximum number of blocks backend is allowed to fall behind
driftTolerance: 1

# list of Stacks API Node endpoints, the endpoint must be reachable by "http://" protocol:
endpoints:
  - stacks-api.stacksdata.info:3999

# The hostname for gateway, all requests must specify this host to be routed to the backend
# e.g http://localhost:8000/extended/v1/block
frontendHostname: localhost
proxyPath: /

kong: http://kong:8001

# Logging settings.
server:
  applicationConnectors:
    - type: http
      useForwardedHeaders: true

  requestLog:
    appenders:
      - type: console

      - type: file
        currentLogFilename: /logs/request.log
        archivedLogFilenamePattern: /logs/request-%d{yyyy-MM-dd}-%i.log.gz
        archivedFileCount: 7
        timeZone: UTC
        maxFileSize: 10MiB
        threshold: INFO
        layout:
          type: access-json

logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  # Logger-specific levels.
  loggers:
    com.stacksonchain: DEBUG
  appenders:
    - type: console

    - type: file
      threshold: INFO
      # logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /logs/application.log
      archivedLogFilenamePattern: /logs/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MiB
      layout:
        type: json
        timestampFormat: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
        includes:
          - level
          - mdc
          - loggerName
          - message
          - exception
          - timestamp
          - callerData
